# Raijin AI - Aider Configuration

conventions: |
  Raijin: Neural processing, Evolution engine, Internet acquisition, Programming domination, Autonomous management, Hardware abstraction layer.
  Use built-in tools. No external API calls.
