#ifndef RAIJIN_NTSTATUS_H
#define RAIJIN_NTSTATUS_H

#include <windows.h>

#ifndef NTSTATUS
typedef LONG NTSTATUS;
#endif

#ifndef NT_SUCCESS
#define NT_SUCCESS(Status) (((NTSTATUS)(Status)) >= 0)
#endif

#ifndef STATUS_SUCCESS
#define STATUS_SUCCESS ((LONG)0)
#endif

#ifndef STATUS_INVALID_PARAMETER
#define STATUS_INVALID_PARAMETER ((LONG)0xC000000D)
#endif

#ifndef STATUS_INSUFFICIENT_RESOURCES
#define STATUS_INSUFFICIENT_RESOURCES ((LONG)0xC000009A)
#endif

#ifndef STATUS_ACCESS_DENIED
#define STATUS_ACCESS_DENIED ((LONG)0xC0000022)
#endif

#ifndef STATUS_UNSUCCESSFUL
#define STATUS_UNSUCCESSFUL ((LONG)0xC0000001)
#endif

#ifndef STATUS_INVALID_DEVICE_STATE
#define STATUS_INVALID_DEVICE_STATE ((LONG)0xC0000184)
#endif

#ifndef STATUS_NOT_SUPPORTED
#define STATUS_NOT_SUPPORTED ((LONG)0xC00000BB)
#endif

#ifndef STATUS_NOT_IMPLEMENTED
#define STATUS_NOT_IMPLEMENTED ((LONG)0xC0000002)
#endif

#ifndef STATUS_NOT_FOUND
#define STATUS_NOT_FOUND ((LONG)0xC0000225)
#endif

#ifndef STATUS_ROLE_BOUNDARY_VIOLATION
#define STATUS_ROLE_BOUNDARY_VIOLATION ((LONG)0xC0001020)
#endif

#endif
